### ISSUE TITLE
Integrate EarthChem repository

### ISSUE THREAD

**Issue by Maurier** [cznethub/dsp#53] opened 2022-04-04 20:37 UTC
**Describe the feature you'd like and what it will do**
Integration of EarthChem repository

**Why is this feature important?**
Part of functional requirements.

**Additional context**
Api endpoints implemented in https://github.com/cznethub/dspback/pull/54
https://github.com/earthchem/ecl-spec/blob/main/schemas/ECL-JSON-v2.0.0.json

**Comment by horsburgh** [comment] 2022-04-12 20:14
Duplicate of #42 so I'll close that one.

**Closed** 2022-05-24 08:12 UTC
Labels: 8, in progress
