### ISSUE TITLE
Error Registering HydroShare Resource in DSP, generic form error

### ISSUE THREAD

**Issue by ClaraCogswell** [cznethub/dsp#110] opened 2023-07-05 13:55 UTC
**Description of the bug**
Received this description on a resource registration error from Ivan Rabak for the following resource: https://www.hydroshare.org/resource/f8199e05ce4f477abebfddc82eb5aa14/

"
_I have a "Boulder Creek" resource that I uploaded directly to HydroShare and I want to register it via Data Submission Portal.

I get a red bottom of the page banner error that the changes cannot be saved. The HydroShare end does not see any errors associated with the resource.

I tried cleaning up the resource for any filename issues. When I create a simple new resource (such still exists under my HydroShare resources) and add some of the files from the offending Boulder Creek resource I am able to register this new resource via the Portal.

If you could save me from recreating the offending resource that would be great! If not, I will go to the "drawing board". Yay :( !

More informative errors beside a simple form check would be really helpful._ "

Steps to reproduce the bug:
1. Go to https://www.hydroshare.org/resource/f8199e05ce4f477abebfddc82eb5aa14/
2. try to register it in the dsp

**Expected behavior**
I think there is nothing about a normal resource that would make it un-registerable with the dsp, I think the issue may not be with his resource.

**Comment by pkdash** [comment] 2023-07-12 21:23
@ClaraCogswell In working with @devincowan on this issue, it seems this resource is currently in a corrupt state - there are files on irods that are missing from django db and vice-versa. We have to co-ordinate with the owner of the resource in order to repair it. Once the resource is fixed we can try registration.

**Comment by devincowan** [comment] 2023-07-12 23:53
Related to https://github.com/hydroshare/hydroshare/issues/5124 and https://github.com/hydroshare/hydroshare/issues/5122

**Comment by ClaraCogswell** [comment] 2023-07-13 12:51
Owner is Ivan Rabak, I can start an email thread with whoever wants to interface with him or all of us and we can get started

**Comment by devincowan** [comment] 2023-07-24 15:53
Partly resolved by @pkdash in https://github.com/hydroshare/hydroshare/issues/5122
However the resource in Hydroshare is "corrupted" due to a failed delete request. Offered to restore the resource from a snapshot but user opted to rebuild manually

**Comment by ClaraCogswell** [comment] 2023-08-21 19:01
We have an update to this, that may merit an issue in the HS workspace as well. Ivan tried to recreate this resource and got a new folder error: 
![thumbnail_image](https://github.com/cznethub/dsp/assets/90924476/bf850bd9-4166-490d-bdc6-6339ad904bdb)
Occurred when he tried to rename a folder

**Comment by devincowan** [comment] 2023-08-21 19:30
I made [a copy and reproduced this issue](https://www.hydroshare.org/resource/82c1ce6b43294b729e528c030b497011/). It is the call to `hsapi/_internal/data-store-rename-file-or-folder/` that times out. Interestingly, the folder appears to rename correctly... tagging @pkdash because I think you have most recent familiarity with folder renaming. Will see if I can reproduce locally
<img width="1792" alt="image" src="https://github.com/cznethub/dsp/assets/17934193/73418ece-bfd5-43ad-b58a-b4434fe10750">
Looks like the folder has ~500 files in it

**Comment by devincowan** [comment] 2023-08-21 20:18
I created https://github.com/hydroshare/hydroshare/issues/5170 to track this, but looks like it will be resolved as the same issue as https://github.com/hydroshare/hydroshare/issues/5158

**Comment by pkdash** [comment] 2023-08-21 21:33
@devincowan Most likely, this code block is causing the timeout error when there are many files in a folder:
https://github.com/hydroshare/hydroshare/blob/develop/hs_core/views/utils.py#L891

**Comment by Maurier** [comment] 2023-09-11 16:30
This will be handled by HydroShare. Depending how it goes, in a future discussion we could consider showing warnings when detecting a large number of files before upload.

**Closed as completed by Maurier** 2023-09-11 16:30 UTC
Labels: 3, completed
