### ISSUE TITLE
Earthchem “Failed to create submission” problem

### ISSUE THREAD

**Issue by cbcunc** [cznethub/dsp#61] opened 2022-07-12 23:29 UTC
**Description of the bug**
Earthchem submission process produced confusing behavior:

Steps to reproduce the bug:
1. Go to my submissions and start a simple EarthChem submission.
2. Fill in required field and click on "submit for review."
3. A red warning box with the message "Failed to create submission" appears at the bottom of the screen with a "Dismiss" button.
4. Message goes away on its own in a few seconds.
5. Click on my submissions produces a message asking if I want to discard the submission.
6. Clicking discard takes me to my submissions where the submission appears after all.
7. Clicking on view submission takes me to ECL where an error page is produced.
8. Logging into ECL, I see the submission in the pending state.

**Expected behavior**
1. No "Failed to create submisision:" message should appear.
2. Clicking on my submissions should not ask me to discard the submission if it's actually there.
3. Clicking on view submission should take me to ECL and show me the pending submission.

**Additional information**
Add any other context about the problem here such as screenshots, software versions, and browser information.

**Comment by devincowan** [comment] 2022-07-12 23:35
Related: I get "Failed to create submission" if I fill in the required items and add either of the following:

- co-author
- funding source

And then "Finish" -> "Finish Later" (note this is different from Chris' "Submit for Review")
![image](https://user-images.githubusercontent.com/17934193/178615712-98cc7ffa-c238-4b79-8138-690f5cf1105c.png)

> Repository exception response[{"timestamp":1657668431683,"status":500,"error":"Internal Server Error","message":"0","path":"/v2/records"}]

Not necessarily surprising, **BUT** the interesting part is: if I just fill the required items without adding one of the above two fields, I can "Finish Later" and the record saves successfully

Probably this is a separate issue but adding it here for now for consideration

**Comment by devincowan** [comment] 2022-07-13 15:46
I created a separate issue for my comment above, #62

**Comment by devincowan** [comment] 2022-07-13 19:03
My issue #62 is resolved by Peng's changes this am, but from what I can tell this issue is still present

**Comment by Maurier** [comment] 2022-07-19 16:18
I could not reproduce this issue. Let me know if it still happens for one of you.

**Comment by devincowan** [comment] 2022-07-19 16:46
confirming fixed for me on dsp-test (though I can't reach https://test-ecl.earthchem.org to verify from the repository side)

**Closed** 2022-07-27 15:35 UTC
Labels: bug
